### ISSUE TITLE
test_external_url.py is failing

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/phylesystem-api#202]
```
../ws-tests/run_tests.sh -t ../../phylesystem-api https://api.opentreeoflife.org
.....sresp.text = {"error": 1, "description": "Expecting study_id as the argument"}
Traceback (most recent call last):
  File "test_external_url.py", line 10, in <module>
    return_bool_data=True)
  File "/Users/jar/a/ot/repo/germinator/ws-tests/opentreetesting.py", line 176, in test_http_json_method
    raise_for_status(resp)
  File "/Users/jar/a/ot/repo/germinator/ws-tests/opentreetesting.py", line 209, in raise_for_status
    raise e
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST
F.sssssss.....s......sss
Passed 17 out of 30 tests.
An 's' means a test was skipped.
Skipped 12 tests.
Failures:  test_external_url.py
```

The .out file has:
```
https://api.opentreeoflife.org/phylesystem/external_url/pg_99
```

**Comment by mtholder** [comment]
fixed in https://github.com/OpenTreeOfLife/phylesystem-api/pull/201
